name: Deploy documentation
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install housemd
        run: pip install .
      - name: Run housemd
        run: |
          mkdir docs/public
          housemd-build housemd-config.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4
        id: deployment
